#!/usr/bin/env python3

with open('pouchdb.js') as f:
	pouchdb = f.read()

with open('wrapper.js') as f:
	wrapper = f.read()

result = wrapper.replace(
	'  /*---a PouchDB build is auto-inserted here---*/',
	pouchdb
)

with open('pouchdb-qml.js', 'w') as f:
	f.write(result)
